spring:
  application:
    name: identityx-api

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:identityxdb
    driverClassName: org.h2.Driver
    username: sa
    password: 12345

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    ms: 360000